{{- if .Values.ingress.enabled -}}
{{- range $g := .Values.ingress.groups }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "linke-calendar.fullname" $ }}-{{ $g.name }}
  labels:
    {{- include "linke-calendar.labels" $ | nindent 4 }}
  {{- with $g.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $.Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with $g.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range $g.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "linke-calendar.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
